/**
 * Streetcred ID Credentials API
 * An API to issue, manage, and verify self-sovereign identity credentials
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Connection invitation parameters
 */
export interface ConnectionInvitationParameters { 
    /**
     * Unique connection identifier. If not specified, a random one will be generated.
     */
    connection_id?: string;
    /**
     * If set to 'true', the invitation can be used by multiple parties and will always have the status set to 'Invited'.  When a party accepts this invitation, a new connection record with a unique identifier will be created.                Default value is 'false'.
     */
    multi_party?: boolean;
}
