/**
 * Streetcred ID Credentials API
 * An API to issue, manage, and verify self-sovereign identity credentials
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgentEndpoint } from './agentEndpoint';
import { ConnectionState } from './connectionState';


export interface ConnectionContract { 
    connectionId?: string;
    name?: string;
    imageUrl?: string;
    myDid?: string;
    theirDid?: string;
    myKey?: string;
    theirKey?: string;
    state?: ConnectionState;
    invitation?: string;
    invitationUrl?: string;
    endpoint?: AgentEndpoint;
    createdAtUtc?: Date;
}
