/**
 * Streetcred ID Credentials API
 * An API to issue, manage, and verify self-sovereign identity credentials
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type CredentialState = 'Offered' | 'Requested' | 'Issued' | 'Rejected' | 'Revoked';

export const CredentialState = {
    Offered: 'Offered' as CredentialState,
    Requested: 'Requested' as CredentialState,
    Issued: 'Issued' as CredentialState,
    Rejected: 'Rejected' as CredentialState,
    Revoked: 'Revoked' as CredentialState
};
