/**
 * Streetcred ID Credentials API
 * An API to issue, manage, and verify self-sovereign identity credentials
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EndorserType } from './endorserType';


/**
 * Issuer Status contract
 */
export interface IssuerStatusContract { 
    /**
     * Transaction Author Agreement Text
     */
    acceptanceText?: string;
    /**
     * Transaction Author Agreement Version
     */
    acceptanceVersion?: string;
    acceptanceDigest?: string;
    acceptanceTime?: number;
    /**
     * Indicates if user needs to accept the   latest agreement on the network
     */
    requireAcceptance?: boolean;
    txnEndorsement?: EndorserType;
    /**
     * Indicates if the user has Endorser status
     */
    issuerCanEndorse?: boolean;
}
