/**
 * Streetcred ID Credentials API
 * An API to issue, manage, and verify self-sovereign identity credentials
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Transaction author agreement
 */
export interface NetworkTxnAgreementContract { 
    /**
     * Acceptance agreement text
     */
    text?: string;
    /**
     * Agreement version
     */
    version?: string;
    /**
     * List of agreement acceptance methods
     */
    acceptanceMethods?: { [key: string]: string; };
}
