/**
 * Streetcred ID Credentials API
 * An API to issue, manage, and verify self-sovereign identity credentials
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProofAttributeInfo } from './proofAttributeInfo';
import { ProofPredicateInfo } from './proofPredicateInfo';
import { RevocationInterval } from './revocationInterval';


export interface ProofRequest { 
    name?: string;
    version?: string;
    nonce?: string;
    requested_attributes?: { [key: string]: ProofAttributeInfo; };
    requested_predicates?: { [key: string]: ProofPredicateInfo; };
    non_revoked?: RevocationInterval;
}
