/**
 * Streetcred ID Credentials API
 * An API to issue, manage, and verify self-sovereign identity credentials
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttributeFilter } from './attributeFilter';
import { RevocationInterval } from './revocationInterval';


export interface ProofPredicateInfo { 
    p_type?: string;
    p_value?: string;
    name?: string;
    restrictions?: Array<AttributeFilter>;
    non_revoked?: RevocationInterval;
}
