/**
 * Streetcred ID Credentials API
 * An API to issue, manage, and verify self-sovereign identity credentials
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EndorserType } from './endorserType';


/**
 * Configuration options for creating new tenant
 */
export interface TenantParameters { 
    /**
     * (Optional) Issuer seed used for deterministic DID generation.  If omitted, a random DID/Key is generated
     */
    issuer_seed?: string;
    /**
     * The name of the tenant.
     */
    name: string;
    /**
     * (Optional) Location of image URL used as profile for this tenant
     */
    image_url?: string;
    /**
     * (Optional) Ledger network identifier. Default is Sovrin Staging (sovrin-staging)
     */
    network_id?: string;
    endorser_type?: EndorserType;
}
