/**
 * Streetcred ID Credentials API
 * An API to issue, manage, and verify self-sovereign identity credentials
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NetworkContract } from './networkContract';
import { TenantExtendedInformationContract } from './tenantExtendedInformationContract';


/**
 * Tenant info.
 */
export interface TenantContract { 
    /**
     * Gets or sets the name.
     */
    name?: string;
    /**
     * Gets or sets the image URI.
     */
    imageUrl?: string;
    network?: NetworkContract;
    /**
     * Gets or sets the tenant identifier.
     */
    tenantId?: string;
    extendedInformation?: TenantExtendedInformationContract;
}
